
services:

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      # - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - redis
      # - elasticsearch

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.worker
    environment:
      - MONGO_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      # - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - redis
      # - elasticsearch

  client:
    build: ./client
    ports:
      - "5173:5173"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"